[project]
name = "ringdowngp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "arviz>=0.23.4",
    "ipykernel>=7.2.0",
    "jax>=0.9.0.1",
    "matplotlib>=3.10.8",
    "numpyro>=0.20.0",
    "seaborn>=0.13.2",
]
